Feature front back infra implementacion diseño aws
andres1397/aik-portal pull request #10
Opened 2020-04-24 07:27 UTC by ManuelCoral1998

Se entrega un diseño con:
- 2 instancias aprovisionadas con saltstack
- 2 grupos de seguridad
- una vpc
- una subnet

2020-04-25 21:21 UTC, juanfe2793 requested changes

2020-04-25 21:21 UTC, juanfe2793 commented on Configuration_Managment/states/yum-s3/files/cob.conf
> +metadata_server = http://169.254.169.254
Esta IP siempre será la misma?

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +  cidr_block = "${var.vpc-cidr}"
Esta forma de escribir esta deprecated. Por favor utilicen Terraform 12. Se los acepto así por ahora, pero en proximos PRs, debe estar actualizado.

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +
Les hace falta:   dar enable al DNS. Es importante para el acceso al portal. Sino quedan con un acceso mediante ip solamente.

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +resource "aws_subnet" "aik-subnet-public" {
De esta manera, hacen un recorrido por las subnets más sencillo: 

  count = length(var.public_subnet_cidr_blocks)
  vpc_id                  = aws_vpc.aik_vpc.id
  cidr_block              = var.public_subnet_cidr_blocks[count.index]
  availability_zone       = var.aws-availability-zones[count.index]
  map_public_ip_on_launch = true

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +  name        = "portal-front-automatizacion-AguirreCoralUrbano"
Cambien el nombre por otro más carto. No es necesario su nombre

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +  user_data = <<-EOF
Recomendación, uticel esta forma: user_data = file("../scripts/jenkins.sh") 

Así puedo traer el user data de otro lado y no queda la plantilla de esta manera. Es una forma más profesional

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/main.tf
> +  key_name               = "${var.aik-key-name}"
Este key name ya se encuentra creado en la cuenta de AWS?

2020-04-25 21:21 UTC, juanfe2793 commented on infraestructura/terraformIaC/variables.tf
> +variable "public-route-table-name" {
Estas variables de nombre, generalmente no tienen como mucho sentido.

2020-05-04 14:35 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +  cidr_block = "${var.vpc-cidr}"
Trabajando en ellos (Buscando plugin)

2020-05-04 14:35 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +
dns hostnames = true

2020-05-04 14:36 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +resource "aws_subnet" "aik-subnet-public" {
No se implemento porque lanzaba el error del plugin, pero ya lo tendremos en cuenta

2020-05-04 14:37 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +  name        = "portal-front-automatizacion-AguirreCoralUrbano"
Se cambio el nombre

2020-05-04 14:37 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +  user_data = <<-EOF
Definitivamente si queda más profesional

2020-05-04 14:37 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/main.tf
> +  key_name               = "${var.aik-key-name}"
Si señor

2020-05-04 14:37 UTC, ManuelCoral1998 commented on infraestructura/terraformIaC/variables.tf
> +variable "public-route-table-name" {
Lo habíamos hecho por orden

2020-05-07 15:27 UTC, merged